import '../styles/global.css'


export const metadata = {
  title: 'Thrillers',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className='p-24'>{children}</body>
    </html>
  )
}
